[package]
name = "epd-waveshare-async"
authors = ["Morgan Roff"]
version = "0.1.0-alpha"
edition = "2021"
description = "Async drivers for Waveshare's e-paper displays."
license = "MIT OR Apache-2.0"

[dependencies]
embedded-graphics = "0.8.1"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
