[package]
name = "epd-waveshare-async"
authors = ["Morgan Roff"]
version = "0.1.0-alpha2"
edition = "2021"
description = "Async drivers for Waveshare's e-paper displays."
license = "MIT OR Apache-2.0"

[dependencies]
defmt = { workspace = true, optional = true }
embedded-graphics.workspace = true
embedded-hal.workspace = true
embedded-hal-async.workspace = true
log = { version = "0.4.27", optional = true }

[features]
default = []
defmt = ["dep:defmt"]
log = ["dep:log"]